// <auto-generated />
using System;
using Autoglass.Architecture.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Autoglass.Architecture.Infra.Data.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20230213181820_Produto")]
    partial class Produto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Layer.Architecture.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CnpjFornecedor")
                        .HasColumnName("CnpjFornecedor")
                        .HasColumnType("int");

                    b.Property<int>("CodFornecedor")
                        .HasColumnName("CodFornecedor")
                        .HasColumnType("int");

                    b.Property<int>("CodProduto")
                        .HasColumnName("CodProduto")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFabricacao")
                        .HasColumnName("DataFabricacao")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnName("DataValidade")
                        .HasColumnType("DateTime");

                    b.Property<string>("DescFornecedor")
                        .IsRequired()
                        .HasColumnName("DescFornecedor")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DescProduto")
                        .IsRequired()
                        .HasColumnName("DescProduto")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Situacao")
                        .HasColumnName("Situacao")
                        .HasColumnType("bool");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
